# Generated by Django 4.1.1 on 2022-09-20 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Drinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("image", models.URLField()),
                ("instructions", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("1", "easy"), ("2", "moderate"), ("3", "advanced")],
                        max_length=2,
                    ),
                ),
                (
                    "liquor_type",
                    models.CharField(
                        choices=[
                            ("W", "Whiskey"),
                            ("V", "Vodka"),
                            ("T", "Tequila"),
                            ("R", "Rum"),
                            ("G", "Gin"),
                            ("B", "Brandy"),
                            ("O", "Other"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drinks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
