# Generated by Django 4.1.1 on 2022-09-20 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("drinks", "0003_ingredient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Glass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="amount",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="drink",
            name="glass",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="drink",
                to="drinks.glass",
            ),
        ),
    ]
