# Generated by Django 4.1.1 on 2022-09-22 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("drinks", "0006_alter_drink_instructions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drink",
            name="glass",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="drink",
                to="drinks.glass",
            ),
        ),
        migrations.AlterField(
            model_name="drink",
            name="instructions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
